import Foundation

/// Pop 的一个插件包：单独编译的功能，要用时从 GitHub 发布页下载装上，不用了可以卸载（见 PluginManager）。
struct PluginPackage: Identifiable, Hashable {
    /// 插件包的 ID，和插件包 Info.plist 里的 PopPluginID 一样，也是发布页上压缩包的名字（plugin-<ID>.zip）
    let id: String
    /// 插件包的文件名（不带 .bundle），和 project.yml 里的 target 名字一样
    let bundleName: String
    let name: String
    let summary: String
    let symbol: String
    let category: BuiltinCategory
    /// 提供的功能（功能 ID）
    let functions: [String]
    /// 存在 UserDefaults 里的偏好，卸载时一起删掉
    var defaultsKeys: [String] = []
}

/// 所有插件包，没装的也在：设置的「插件」页按它列出来，没装上也知道插件包叫什么、提供哪些功能。
enum PluginCatalog {
    static let packages: [PluginPackage] = [
        PluginPackage(id: "screenPen", bundleName: "PopScreenPen", name: String(localized: "屏幕画笔"),
                      summary: String(localized: "演示、录教程时直接在屏幕上画：画笔、荧光笔、箭头、方框、椭圆，笔迹可以几秒后自动消失，也可以留着去操作下面的窗口，录屏时一起录进去；Esc 或再用一次结束"),
                      symbol: "scribble.variable", category: .recording, functions: [BuiltinPluginID.screenPen]),
        PluginPackage(id: "cameraBubble", bundleName: "PopCameraBubble", name: String(localized: "摄像头小窗"),
                      summary: String(localized: "在屏幕角落用一个圆形小窗显示摄像头画面，录教程、演示时把自己也放进画面；拖动换位置，滚动或双击换大小，右键换形状和摄像头。再用一次关闭"),
                      symbol: "person.crop.circle", category: .recording, functions: [BuiltinPluginID.cameraBubble],
                      // 和插件包里 CameraBubble 的键一样
                      defaultsKeys: ["pop.cameraBubble.size", "pop.cameraBubble.shape"]),
        PluginPackage(id: "pointerHighlight", bundleName: "PopPointerHighlight", name: String(localized: "突出显示指针"),
                      summary: String(localized: "演示、录教程时在指针周围加一圈黄色光圈，按下鼠标时泛起波纹，让人一眼看到指针在哪；再用一次关闭"),
                      symbol: "cursorarrow.rays", category: .recording, functions: [BuiltinPluginID.pointerHighlight]),
        PluginPackage(id: "teleprompter", bundleName: "PopTeleprompter", name: String(localized: "提词器"),
                      summary: String(localized: "把选中的稿子放进屏幕上方的提词器，按设好的速度慢慢往上滚，对着摄像头读；空格暂停，↑↓ 调速度，录屏时不会录进去"),
                      symbol: "text.aligncenter", category: .recording, functions: [BuiltinPluginID.teleprompter],
                      // 和插件包里 TeleprompterModel 的键一样
                      defaultsKeys: ["pop.teleprompter.speed", "pop.teleprompter.fontSize"]),
        PluginPackage(id: "cleanKeyboard", bundleName: "PopKeyboardCleaner", name: String(localized: "清洁键盘"),
                      summary: String(localized: "锁住键盘一分钟，擦键盘时不会误触；亮度、音量键也不起作用，用鼠标点「结束清洁」随时恢复"),
                      symbol: "keyboard", category: .files, functions: [BuiltinPluginID.cleanKeyboard]),
        PluginPackage(id: "ruler", bundleName: "PopScreenRuler", name: String(localized: "屏幕标尺"),
                      summary: String(localized: "定格屏幕，量出指针处到上下左右边缘的距离，拖动量一块区域的宽高；单击复制尺寸"),
                      symbol: "ruler", category: .screen, functions: [BuiltinPluginID.ruler]),
        PluginPackage(id: "largeType", bundleName: "PopLargeType", name: String(localized: "大字显示"),
                      summary: String(localized: "把选中的文字铺满整个屏幕，给别人看电话号码、Wi-Fi 密码、取件码都方便；点一下或按任意键关闭"),
                      symbol: "textformat.size", category: .text, functions: [BuiltinPluginID.largeType]),
        PluginPackage(id: "spellCheck", bundleName: "PopSpellCheck", name: String(localized: "拼写检查"),
                      summary: String(localized: "找出外文里拼错的词，给出改法，可以直接换成改好的文字（系统自带的拼写检查，离线）"),
                      symbol: "text.badge.checkmark", category: .text, functions: [BuiltinPluginID.spellCheck]),
        PluginPackage(id: "codeImage", bundleName: "PopCodeImage", name: String(localized: "代码截图"),
                      summary: String(localized: "把选中的代码画成一张图片（深色编辑器、语法着色、渐变背景），可以复制、存储或贴到屏幕上"),
                      symbol: "chevron.left.forwardslash.chevron.right", category: .developer, functions: [BuiltinPluginID.codeImage]),
        PluginPackage(id: "cron", bundleName: "PopCron", name: String(localized: "Cron 表达式"),
                      summary: String(localized: "把 cron 表达式（比如 */15 9-17 * * 1-5）说成中文，列出接下来几次运行的时间"),
                      symbol: "clock.arrow.circlepath", category: .developer, functions: [BuiltinPluginID.cron]),
        PluginPackage(id: "jsonTypes", bundleName: "PopJSONTypes", name: String(localized: "JSON 转代码"),
                      summary: String(localized: "根据选中的 JSON 生成 TypeScript、Swift、Go、Kotlin 的类型定义"),
                      symbol: "curlybraces.square", category: .developer, functions: [BuiltinPluginID.jsonTypes]),
        PluginPackage(id: "regexTest", bundleName: "PopRegexTester", name: String(localized: "正则测试"),
                      summary: String(localized: "在选中的文字里试正则表达式：实时标出每处匹配、列出分组，也可以试替换"),
                      symbol: "asterisk.circle", category: .developer, functions: [BuiltinPluginID.regexTest]),
        PluginPackage(id: "watermark", bundleName: "PopWatermark", name: String(localized: "加水印"),
                      summary: String(localized: "给选中的图片或 PDF 斜着铺满一层半透明的文字（比如「仅供办理业务使用」），另存一份放在原文件旁边"),
                      symbol: "signature", category: .screen, functions: [BuiltinPluginID.watermark],
                      defaultsKeys: ["watermarkText"]),
        PluginPackage(id: "palette", bundleName: "PopPalette", name: String(localized: "图片配色"),
                      summary: String(localized: "找出图片里的主要颜色，按面积从大到小列出色值，点一下复制"),
                      symbol: "paintpalette", category: .screen, functions: [BuiltinPluginID.palette]),
        PluginPackage(id: "tableOCR", bundleName: "PopTableOCR", name: String(localized: "识别表格"),
                      summary: String(localized: "识别截图或图片里的表格，转成 Markdown 表格、CSV 或者制表符分隔（macOS 26；更早的系统按普通文字识别）"),
                      symbol: "tablecells", category: .screen, functions: [BuiltinPluginID.tableOCR]),
        PluginPackage(id: "numberStats", bundleName: "PopNumberStats", name: String(localized: "数字统计"),
                      summary: String(localized: "选中一列或一串数字，算出合计、平均、中位数、最大、最小"),
                      symbol: "sum", category: .convert, functions: [BuiltinPluginID.numberStats]),
        PluginPackage(id: "reminder", bundleName: "PopReminder", name: String(localized: "加到提醒事项"),
                      summary: String(localized: "从选中的文字里认出时间（明天下午 3 点、周五、10 月 8 日、半小时后……），加到「提醒事项」或者「日历」"),
                      symbol: "checklist", category: .text, functions: [BuiltinPluginID.reminder]),
        PluginPackage(id: "codeStats", bundleName: "PopCodeStats", name: String(localized: "代码行数"),
                      summary: String(localized: "按语言统计选中的文件夹里有多少个代码文件、多少行，可以复制成 Markdown 表格"),
                      symbol: "chevron.left.forwardslash.chevron.right", category: .files, functions: [BuiltinPluginID.codeStats]),
        PluginPackage(id: "compareFiles", bundleName: "PopFileCompare", name: String(localized: "对比文件"),
                      summary: String(localized: "对比选中的两个文本文件（代码、Markdown、配置、CSV……），标出删去和新增的行，改动的地方逐词标出；按修改时间，旧的当原文"),
                      symbol: "doc.on.doc", category: .files, functions: [BuiltinPluginID.compareFiles]),
        PluginPackage(id: "folderTools", bundleName: "PopFolderTools", name: String(localized: "文件夹工具"),
                      summary: String(localized: "看文件夹里哪些东西最占地方、找出内容一样的重复文件、比较两个文件夹有哪些不同，不要的可以移到废纸篓"),
                      symbol: "folder.badge.gearshape", category: .files, functions: [BuiltinPluginID.diskUsage, BuiltinPluginID.findDuplicates, BuiltinPluginID.compareFolders]),
        PluginPackage(id: "batchRename", bundleName: "PopBatchRename", name: String(localized: "批量重命名"),
                      summary: String(localized: "给选中的文件统一改名：编号、替换文字、加前后缀、按照片的拍摄时间、改大小写，先看预览再改，改完可以撤销"),
                      symbol: "rectangle.and.pencil.and.ellipsis", category: .files, functions: [BuiltinPluginID.batchRename]),
        PluginPackage(id: "menuShortcuts", bundleName: "PopMenuShortcuts", name: String(localized: "快捷键一览"),
                      summary: String(localized: "列出当前 App 菜单里的所有快捷键，可以搜索，点一项直接执行"),
                      symbol: "command", category: .files, functions: [BuiltinPluginID.menuShortcuts]),
        PluginPackage(id: "windowLayout", bundleName: "PopWindowLayout", name: String(localized: "窗口布局"),
                      summary: String(localized: "把当前窗口放到屏幕的左半边、右半边、三分之一、最大化、居中，或者移到另一个显示器"),
                      symbol: "rectangle.split.2x1", category: .files, functions: [BuiltinPluginID.windowLayout]),
        PluginPackage(id: "speak", bundleName: "PopSpeak", name: String(localized: "朗读"),
                      summary: String(localized: "用系统语音朗读选中的文字，朗读中再用一次就停止；也能读出来存成音频文件"),
                      symbol: "speaker.wave.2", category: .text, functions: [BuiltinPluginID.speak, BuiltinPluginID.speakToFile]),
        PluginPackage(id: "textImage", bundleName: "PopTextImage", name: String(localized: "文字转图片"),
                      summary: String(localized: "把选中的文字排成一张手机上看着舒服的长图（宽 1080 像素），白底、米黄、深色三种底色，可以复制、存储或贴到屏幕上"),
                      symbol: "text.below.photo", category: .text, functions: [BuiltinPluginID.textImage]),
        PluginPackage(id: "webCapture", bundleName: "PopWebCapture", name: String(localized: "网页存档"),
                      summary: String(localized: "把选中的网址整页存成一页长 PDF（文字能选、能搜）、一张长图，或者只把正文存成 Markdown，放在「下载」里"),
                      symbol: "arrow.down.doc", category: .text, functions: [BuiltinPluginID.webCapture]),
        PluginPackage(id: "extractInfo", bundleName: "PopExtractInfo", name: String(localized: "提取信息"),
                      summary: String(localized: "从一段文字里找出链接、邮箱、电话号码和 IP 地址，逐个复制或者一起复制"),
                      symbol: "text.magnifyingglass", category: .text, functions: [BuiltinPluginID.extractInfo]),
        PluginPackage(id: "idNumber", bundleName: "PopIDNumber", name: String(localized: "证件号码"),
                      summary: String(localized: "身份证号、统一社会信用代码、银行卡号：检查校验位，读出出生日期、年龄、性别、地区和登记管理部门，不联网"),
                      symbol: "person.text.rectangle", category: .text, functions: [BuiltinPluginID.idNumber]),
        PluginPackage(id: "lineTools", bundleName: "PopLineTools", name: String(localized: "按行处理"),
                      summary: String(localized: "一列文字加引号和逗号（SQL 的 IN 列表）、转 JSON 数组、加减序号、倒序、打乱；一行用逗号隔开的拆成多行"),
                      symbol: "list.bullet.rectangle", category: .text, functions: [BuiltinPluginID.lineTools]),
        PluginPackage(id: "textCleanup", bundleName: "PopTextCleanup", name: String(localized: "文字整理"),
                      summary: String(localized: "合并换行、去掉空行和多余空格、中英文之间加空格、全角转半角、简繁转换、拼音、按行排序去重"),
                      symbol: "text.alignleft", category: .text, functions: [BuiltinPluginID.textCleanup]),
        PluginPackage(id: "quickNote", bundleName: "PopQuickNote", name: String(localized: "收集箱"),
                      summary: String(localized: "把选中的文字追加到「文稿/Pop 收集箱.md」"),
                      symbol: "tray.and.arrow.down", category: .text, functions: [BuiltinPluginID.quickNote]),
        PluginPackage(id: "changeCase", bundleName: "PopChangeCase", name: String(localized: "大小写"),
                      summary: String(localized: "大写、小写、驼峰、下划线等写法互相转换"),
                      symbol: "textformat", category: .convert, functions: [BuiltinPluginID.changeCase]),
        PluginPackage(id: "encodeDecode", bundleName: "PopEncodeDecode", name: String(localized: "编码转换"),
                      summary: String(localized: "Base64、URL、Unicode、HTML 实体的编码和解码"),
                      symbol: "chevron.left.forwardslash.chevron.right", category: .convert, functions: [BuiltinPluginID.encodeDecode]),
        PluginPackage(id: "yamlJSON", bundleName: "PopYAMLJSON", name: String(localized: "YAML 和 JSON"),
                      summary: String(localized: "选中 JSON 转成 YAML，选中 YAML 转成 JSON，键的顺序不变"),
                      symbol: "arrow.left.arrow.right.square", category: .convert, functions: [BuiltinPluginID.yamlJSON]),
        PluginPackage(id: "formatXML", bundleName: "PopFormatXML", name: String(localized: "XML 格式化"),
                      summary: String(localized: "格式化或压缩选中的 XML（也认 SVG、plist、XHTML）"),
                      symbol: "chevron.left.forwardslash.chevron.right", category: .convert, functions: [BuiltinPluginID.formatXML]),
        PluginPackage(id: "formatSQL", bundleName: "PopFormatSQL", name: String(localized: "SQL 格式化"),
                      summary: String(localized: "把选中的 SQL 按子句分行、关键字大写、子查询缩进，也可以压成一行"),
                      symbol: "cylinder.split.1x2", category: .convert, functions: [BuiltinPluginID.formatSQL]),
        PluginPackage(id: "tableConvert", bundleName: "PopTableConvert", name: String(localized: "表格转换"),
                      summary: String(localized: "从表格软件复制的文字、CSV、Markdown 表格互相转换，也能转成 JSON"),
                      symbol: "tablecells", category: .convert, functions: [BuiltinPluginID.tableConvert]),
        PluginPackage(id: "markdown", bundleName: "PopMarkdown", name: String(localized: "Markdown 富文本"),
                      summary: String(localized: "把选中的 Markdown 显示成排好版的样子，或者转成带格式的文字复制下来，粘贴到文稿、邮件、备忘录里保留格式"),
                      symbol: "doc.richtext", category: .convert, functions: [BuiltinPluginID.markdownPreview, BuiltinPluginID.markdownCopy]),
        PluginPackage(id: "toMarkdown", bundleName: "PopToMarkdown", name: String(localized: "转成 Markdown"),
                      summary: String(localized: "把网页、文档里选中的带格式文字转成 Markdown：标题、列表、链接、粗体、代码、表格"),
                      symbol: "doc.plaintext", category: .convert, functions: [BuiltinPluginID.toMarkdown]),
        PluginPackage(id: "markdownTOC", bundleName: "PopMarkdownTOC", name: String(localized: "Markdown 目录"),
                      summary: String(localized: "按选中的 Markdown 里的标题生成目录，点链接能跳到对应的标题（锚点和 GitHub 的写法一样）"),
                      symbol: "list.bullet.rectangle", category: .convert, functions: [BuiltinPluginID.markdownTOC]),
        PluginPackage(id: "dateSpan", bundleName: "PopDateSpan", name: String(localized: "日期计算"),
                      summary: String(localized: "选中两个日期（比如「2026-09-29 到 2026-12-25」），算出相差多少天、几周、几个月，其中有多少个工作日"),
                      symbol: "calendar.badge.clock", category: .convert, functions: [BuiltinPluginID.dateSpan]),
        PluginPackage(id: "numberConvert", bundleName: "PopNumberConvert", name: String(localized: "数字转换"),
                      summary: String(localized: "进制转换、千分位、人民币大写"),
                      symbol: "number.circle", category: .convert, functions: [BuiltinPluginID.numberConvert]),
        PluginPackage(id: "contrast", bundleName: "PopContrast", name: String(localized: "对比度"),
                      summary: String(localized: "选中两个颜色（比如「#333333 #FFFFFF」），算出文字和背景的对比度，看是否达到 WCAG 的 AA、AAA"),
                      symbol: "circle.lefthalf.filled", category: .convert, functions: [BuiltinPluginID.contrast]),
        PluginPackage(id: "hash", bundleName: "PopHash", name: String(localized: "哈希"),
                      summary: String(localized: "计算文字或文件的 MD5、SHA-1、SHA-256、SHA-512"),
                      symbol: "number.square", category: .developer, functions: [BuiltinPluginID.hash]),
        PluginPackage(id: "qrCode", bundleName: "PopQRCode", name: String(localized: "二维码"),
                      summary: String(localized: "把文字或链接生成二维码（英文字母和数字还能生成条形码）；选中图片时识别里面的二维码和条形码"),
                      symbol: "qrcode", category: .developer, functions: [BuiltinPluginID.qrCode]),
        PluginPackage(id: "base64Image", bundleName: "PopBase64Image", name: String(localized: "Base64 图片"),
                      summary: String(localized: "把 Base64 或 data: 开头的图片数据显示成图片，可以复制、保存、贴到屏幕"),
                      symbol: "photo.artframe", category: .developer, functions: [BuiltinPluginID.base64Image]),
        PluginPackage(id: "random", bundleName: "PopRandom", name: String(localized: "随机生成"),
                      summary: String(localized: "生成 UUID、密码和随机数字，可以直接粘贴到当前输入框"),
                      symbol: "dice", category: .developer, functions: [BuiltinPluginID.random]),
        PluginPackage(id: "linkInspect", bundleName: "PopLinkInspect", name: String(localized: "链接解析"),
                      summary: String(localized: "拆开链接的协议、主机、路径和每个参数（解码后），去掉 utm_source 这类跟踪参数"),
                      symbol: "link", category: .developer, functions: [BuiltinPluginID.linkInspect]),
        PluginPackage(id: "jwtDecode", bundleName: "PopJWT", name: String(localized: "JWT 解码"),
                      summary: String(localized: "解码选中的 JWT，列出签发者、过期时间等声明（只解码，不验证签名）"),
                      symbol: "key", category: .developer, functions: [BuiltinPluginID.jwtDecode]),
        PluginPackage(id: "charInfo", bundleName: "PopCharInfo", name: String(localized: "字符信息"),
                      summary: String(localized: "查看每个字符的 Unicode 码点、名称和编码；找出并去掉零宽空格这类看不见的字符"),
                      symbol: "character.magnify", category: .developer, functions: [BuiltinPluginID.charInfo]),
        PluginPackage(id: "screenshotTranslate", bundleName: "PopScreenshotTranslate", name: String(localized: "截图翻译"),
                      summary: String(localized: "框选屏幕上的一块区域，识别里面的文字并翻译（离线）"),
                      symbol: "translate", category: .text, functions: [BuiltinPluginID.screenshotTranslate]),
        PluginPackage(id: "textDiff", bundleName: "PopTextDiff", name: String(localized: "文本对比"),
                      summary: String(localized: "把选中的文字和剪贴板里的文字对比，标出删去和新增的地方"),
                      symbol: "arrow.left.arrow.right.square", category: .text, functions: [BuiltinPluginID.textDiff]),
        PluginPackage(id: "imageConvert", bundleName: "PopImageConvert", name: String(localized: "图片转换"),
                      summary: String(localized: "把选中的图片文件转成 PNG、JPEG、HEIC，缩小一半、压缩体积或者压到指定大小以内，旋转、左右翻转，或者去掉照片里的位置和拍摄信息；结果存在原图旁边"),
                      symbol: "photo.on.rectangle.angled", category: .screen, functions: [BuiltinPluginID.imageConvert]),
        PluginPackage(id: "stitchImages", bundleName: "PopStitchImages", name: String(localized: "拼接图片"),
                      summary: String(localized: "把选中的几张图片按文件名的顺序竖着或者横着拼成一张，或者合成一张动图，存在第一张旁边"),
                      symbol: "square.split.1x2", category: .screen, functions: [BuiltinPluginID.stitchImages]),
        PluginPackage(id: "idPhoto", bundleName: "PopIDPhoto", name: String(localized: "证件照"),
                      summary: String(localized: "把人像照片换成白底、蓝底或红底，按人脸位置裁成一寸、二寸（300 dpi）；在本机处理，另存一份放在原图旁边"),
                      symbol: "person.crop.rectangle", category: .screen, functions: [BuiltinPluginID.idPhoto]),
        PluginPackage(id: "cropImage", bundleName: "PopCropImage", name: String(localized: "裁剪图片"),
                      summary: String(localized: "把选中的图片裁成 1:1、4:3、3:4、16:9、9:16，自动对准画面里的主体；另存一份放在原图旁边"),
                      symbol: "crop", category: .screen, functions: [BuiltinPluginID.cropImage]),
        PluginPackage(id: "redact", bundleName: "PopRedact", name: String(localized: "隐私打码"),
                      summary: String(localized: "找出选中图片里的人脸、电话号码、邮箱、身份证号、银行卡号和车牌，打上马赛克另存一份；在本机识别，另存的那份不带拍摄信息和位置"),
                      symbol: "eye.slash", category: .screen, functions: [BuiltinPluginID.redact]),
        PluginPackage(id: "removeBackground", bundleName: "PopRemoveBackground", name: String(localized: "抠图"),
                      summary: String(localized: "去掉选中图片的背景，只留下人、动物或物品（离线）"),
                      symbol: "wand.and.stars", category: .screen, functions: [BuiltinPluginID.removeBackground]),
        PluginPackage(id: "scanCode", bundleName: "PopScanCode", name: String(localized: "扫码"),
                      summary: String(localized: "框选屏幕上的二维码或条形码，识别里面的内容；链接可以直接打开，Wi-Fi 二维码列出密码"),
                      symbol: "qrcode.viewfinder", category: .screen, functions: [BuiltinPluginID.scanCode]),
        PluginPackage(id: "screenRecord", bundleName: "PopScreenRecord", name: String(localized: "录屏"),
                      summary: String(localized: "拖出一块区域、单击选一个窗口或者按回车录整个屏幕，存成 MP4；可以录上电脑里的声音或者麦克风、显示鼠标点击和按下的键，录好能接着转成 GIF。正在录的时候再用一次就停止"),
                      symbol: "record.circle", category: .recording, functions: [BuiltinPluginID.screenRecord]),
        PluginPackage(id: "scrollCapture", bundleName: "PopScrollCapture", name: String(localized: "滚动截图"),
                      summary: String(localized: "框选一块区域，一边往下滚动一边截，拼成一张长图；网页、聊天记录、长文档都能截全，还能接着识别文字。正在截的时候再用一次就是完成"),
                      symbol: "scroll", category: .recording, functions: [BuiltinPluginID.scrollCapture]),
        PluginPackage(id: "showKeystrokes", bundleName: "PopShowKeystrokes", name: String(localized: "显示按键"),
                      summary: String(localized: "演示、录教程时在屏幕下方显示按下的组合键（⌘C、⇧⌘4、方向键这些），普通打字不显示；再用一次关闭。录屏时也可以勾选一起录进去"),
                      symbol: "command.square", category: .recording, functions: [BuiltinPluginID.showKeystrokes]),
        PluginPackage(id: "folderTree", bundleName: "PopFolderTree", name: String(localized: "目录结构"),
                      summary: String(localized: "把选中文件夹里的目录结构写成树形或者 Markdown 列表，贴进文档、README 或者发给别人"),
                      symbol: "list.bullet.indent", category: .files, functions: [BuiltinPluginID.folderTree]),
        PluginPackage(id: "zip", bundleName: "PopZip", name: String(localized: "压缩和解压"),
                      summary: String(localized: "把选中的文件或文件夹压缩成 zip，存在原来的文件夹里；把选中的 zip 解压到旁边的同名文件夹里"),
                      symbol: "doc.zipper", category: .files, functions: [BuiltinPluginID.zip, BuiltinPluginID.unzip]),
        PluginPackage(id: "pdf", bundleName: "PopPDF", name: String(localized: "PDF"),
                      summary: String(localized: "把选中的图片和 PDF 按文件名顺序合成一个 PDF；只选了一个 PDF 时可以把每页存成图片、复制里面的文字、取出其中几页或者拆开、加密码或者去掉密码，或者压缩"),
                      symbol: "doc.richtext", category: .files, functions: [BuiltinPluginID.pdf]),
        PluginPackage(id: "videoConvert", bundleName: "PopVideoConvert", name: String(localized: "视频转换"),
                      summary: String(localized: "把选中的视频转成 GIF、转成 MP4、压缩到 720p、提取音频，或者均匀取 16 帧拼成一张缩略图；结果存在原视频旁边"),
                      symbol: "film", category: .files, functions: [BuiltinPluginID.videoConvert]),
        PluginPackage(id: "trimMedia", bundleName: "PopTrimMedia", name: String(localized: "截取片段"),
                      summary: String(localized: "截取选中的音频或视频的一段（写上开始和结束的时间），存在原文件旁边"),
                      symbol: "scissors", category: .files, functions: [BuiltinPluginID.trimMedia]),
        PluginPackage(id: "transcribe", bundleName: "PopTranscribe", name: String(localized: "语音转文字"),
                      summary: String(localized: "把录音、视频里说的话转成文字和 SRT 字幕，存在原文件旁边；普通话、英语、粤语、日语，这台 Mac 支持时在本机识别"),
                      symbol: "captions.bubble", category: .files, functions: [BuiltinPluginID.transcribe]),
        PluginPackage(id: "airDrop", bundleName: "PopAirDrop", name: String(localized: "隔空投送"),
                      summary: String(localized: "用隔空投送把选中的文件、图片、链接或文字发到附近的 iPhone、iPad 或 Mac"),
                      symbol: "dot.radiowaves.left.and.right", category: .files, functions: [BuiltinPluginID.airDrop]),
        PluginPackage(id: "sendToPhone", bundleName: "PopSendToPhone", name: String(localized: "传到手机"),
                      summary: String(localized: "手机扫码下载选中的文件、图片（文件夹先打包成 zip）或者拿到选中的文字，也能从手机传文件到「下载」文件夹；手机和 Mac 连同一个 Wi-Fi 就行，安卓手机也能用"),
                      symbol: "iphone.radiowaves.left.and.right", category: .files, functions: [BuiltinPluginID.sendToPhone]),
        PluginPackage(id: "openInTerminal", bundleName: "PopOpenInTerminal", name: String(localized: "在终端打开"),
                      summary: String(localized: "在「终端」里打开选中的文件夹（选中文件时打开它所在的文件夹）"),
                      symbol: "apple.terminal", category: .files, functions: [BuiltinPluginID.openInTerminal]),
        PluginPackage(id: "keepAwake", bundleName: "PopKeepAwake", name: String(localized: "保持唤醒"),
                      summary: String(localized: "一段时间内不让屏幕变暗、电脑睡眠，适合看文档、演示、等下载"),
                      symbol: "cup.and.saucer", category: .files, functions: [BuiltinPluginID.keepAwake]),
        PluginPackage(id: "systemActions", bundleName: "PopSystemActions", name: String(localized: "系统操作"),
                      summary: String(localized: "锁屏、熄屏、睡眠、打开屏幕保护程序、切换深色和浅色模式、静音、隐藏或显示桌面图标、显示隐藏文件、推出所有磁盘"),
                      symbol: "switch.2", category: .files, functions: [BuiltinPluginID.systemActions]),
        PluginPackage(id: "timer", bundleName: "PopTimer", name: String(localized: "计时器"),
                      summary: String(localized: "倒计时：选一个时长，或者选中「25 分钟」「1:30」这样的文字直接开始；到点时响一声、发通知。也有番茄钟：专注 25 分钟、休息 5 分钟，一直循环"),
                      symbol: "timer", category: .files, functions: [BuiltinPluginID.timer]),
        PluginPackage(id: "spotlight", bundleName: "PopSpotlight", name: String(localized: "聚光灯"),
                      summary: String(localized: "演示、录教程时把屏幕压暗，只亮着指针周围一圈，跟着指针走，让大家看你指的地方；录屏时一起录进去，再用一次关闭"),
                      symbol: "flashlight.on.fill", category: .recording, functions: [BuiltinPluginID.spotlight]),
        PluginPackage(id: "beautify", bundleName: "PopBeautify", name: String(localized: "截图美化"),
                      summary: String(localized: "给截图加上渐变背景、留白、圆角和阴影，可以补成 1:1、4:3、16:9，发文章、做演示更好看；选中图片就用它，没选中就先框选屏幕上的一块"),
                      symbol: "wand.and.stars", category: .screen, functions: [BuiltinPluginID.beautify],
                      // 和插件包里 ScreenshotBeautifier.Options 的键一样
                      defaultsKeys: ["pop.beautify.background", "pop.beautify.padding", "pop.beautify.ratio", "pop.beautify.corners", "pop.beautify.shadow"]),
        PluginPackage(id: "zoom", bundleName: "PopZoom", name: String(localized: "屏幕放大"),
                      summary: String(localized: "演示、录教程时把指针附近放大，看清小字：放大的是那一刻的屏幕画面，挪动指针换地方看，滚轮或 ↑↓ 调倍数，点一下或按 Esc 回去"),
                      symbol: "plus.magnifyingglass", category: .recording, functions: [BuiltinPluginID.zoom]),
        PluginPackage(id: "compareImages", bundleName: "PopCompareImages", name: String(localized: "对比图片"),
                      summary: String(localized: "对比选中的两张图片：并排、滑动分界线、半透明叠加，或者把不一样的像素标红、框出几处不同；改版前后的截图、设计稿和实现对照都用得上"),
                      symbol: "square.split.2x1", category: .screen, functions: [BuiltinPluginID.compareImages],
                      // 和插件包里 ImageCompareModel 的键一样
                      defaultsKeys: ["pop.compareImages.mode", "pop.compareImages.ignoreSubtle"]),
        PluginPackage(id: "splitImage", bundleName: "PopSplitImage", name: String(localized: "切分图片"),
                      summary: String(localized: "把选中的图片切成九宫格、四宫格（对准画面里的主体裁成正方形）或者横着三张，长图切成几页；按发出去的顺序编号，存在原图旁边的文件夹里"),
                      symbol: "square.grid.3x3", category: .screen, functions: [BuiltinPluginID.splitImage],
                      // 和插件包里 SplitImageModel 的键一样
                      defaultsKeys: ["pop.splitImage.layout"]),
        PluginPackage(id: "quitApps", bundleName: "PopQuitApps", name: String(localized: "退出 App"),
                      summary: String(localized: "列出正在运行的 App 和各占多少内存，一键退出，没有响应的强制退出；也能一下退出其他所有 App，开会、演示前清清场"),
                      symbol: "xmark.app", category: .files, functions: [BuiltinPluginID.quitApps]),
        PluginPackage(id: "tidyFolder", bundleName: "PopTidyFolder", name: String(localized: "整理文件夹"),
                      summary: String(localized: "把选中的文件夹（没选时是「下载」）第一层的文件按类型或者按月份归到子文件夹里，照片和视频也能按拍摄日期归好；先看预览，整理完可以撤销"),
                      symbol: "folder.badge.gearshape", category: .files, functions: [BuiltinPluginID.tidyFolder],
                      // 和插件包里 TidyFolderModel 的键一样
                      defaultsKeys: ["pop.tidyFolder.mode"]),
        PluginPackage(id: "appIcon", bundleName: "PopAppIcon", name: String(localized: "生成图标"),
                      summary: String(localized: "用选中的图片生成 App 图标：macOS 的 .icns 和 Xcode 用的图标集（圆角方块，和系统 App 的图标一样大）、iOS 的 1024 图标，还有网站的 favicon，存在原图旁边的文件夹里"),
                      symbol: "app.dashed", category: .screen, functions: [BuiltinPluginID.appIcon],
                      // 和插件包里 AppIconModel 的键一样
                      defaultsKeys: ["pop.appIcon.style", "pop.appIcon.fill", "pop.appIcon.outputs"]),
        PluginPackage(id: "uninstallApp", bundleName: "PopUninstallApp", name: String(localized: "卸载 App"),
                      summary: String(localized: "卸载选中的 App：连同它在「资源库」里留下的设置、缓存、容器一起找出来，看清各占多大，再一起移到废纸篓；只勾留下的文件，就是把 App 恢复成刚装好的样子"),
                      symbol: "trash.square", category: .files, functions: [BuiltinPluginID.uninstallApp]),
        PluginPackage(id: "newFile", bundleName: "PopNewFile", name: String(localized: "新建文件"),
                      summary: String(localized: "在选中的文件夹（没选时是访达当前的文件夹）里新建文本、Markdown、网页、脚本这些文件，也可以把选中的文字、剪贴板里的文字和图片直接存成文件"),
                      symbol: "doc.badge.plus", category: .files, functions: [BuiltinPluginID.newFile],
                      // 和插件包里 NewFileModel 的键一样
                      defaultsKeys: ["pop.newFile.kind"]),
        PluginPackage(id: "fileEncoding", bundleName: "PopFileEncoding", name: String(localized: "文件编码"),
                      summary: String(localized: "认出选中的文本文件是什么编码（UTF-8、GBK、Big5……）、用的什么换行，一键转成 UTF-8（Excel 打开 CSV 要带 BOM）或者 GBK，换行统一成 LF 或 CRLF；转完可以撤销"),
                      symbol: "character.book.closed", category: .files, functions: [BuiltinPluginID.fileEncoding],
                      // 和插件包里 FileEncodingModel 的键一样
                      defaultsKeys: ["pop.fileEncoding.target", "pop.fileEncoding.lines"]),
        PluginPackage(id: "appInfo", bundleName: "PopAppInfo", name: String(localized: "App 信息"),
                      summary: String(localized: "看选中的 App 是给哪种芯片做的、谁签的名、有没有公证、在不在沙盒里、会要哪些权限、用什么做的、从哪下载的，可以复制下来"),
                      symbol: "info.square", category: .files, functions: [BuiltinPluginID.appInfo]),
        PluginPackage(id: "similarPhotos", bundleName: "PopSimilarPhotos", name: String(localized: "相似照片"),
                      summary: String(localized: "在选中的文件夹（或者几张图片）里找出连拍、重复存的、改过大小的相似照片，每组留最清楚的一张，其余的移到废纸篓"),
                      symbol: "photo.stack", category: .files, functions: [BuiltinPluginID.similarPhotos],
                      // 和插件包里 SimilarPhotosModel 的键一样
                      defaultsKeys: ["pop.similarPhotos.sensitivity"]),
        PluginPackage(id: "mediaInfo", bundleName: "PopMediaInfo", name: String(localized: "媒体信息"),
                      summary: String(localized: "看选中的视频或音频用的什么编码、分辨率、帧率、码率，是不是 HDR，有几条音轨和字幕，用什么设备在哪拍的；带着拍摄地点时可以去掉位置另存一份"),
                      symbol: "film.stack", category: .files, functions: [BuiltinPluginID.mediaInfo]),
        PluginPackage(id: "subtitles", bundleName: "PopSubtitles", name: String(localized: "字幕工具"),
                      summary: String(localized: "选中字幕文件（SRT、WebVTT、ASS、LRC），整体提前或推后、换帧率、去掉样式标签和听障说明，转成 SRT、WebVTT、LRC 或纯文字；选两份字幕可以合成一份双语字幕"),
                      symbol: "captions.bubble", category: .files, functions: [BuiltinPluginID.subtitles]),
        PluginPackage(id: "fontPreview", bundleName: "PopFontPreview", name: String(localized: "字体预览"),
                      summary: String(localized: "用这台 Mac 上的每一种字体显示选中的文字（没选中时用示例），按中文、西文、等宽、收藏筛选，只看能完整显示的；复制字体名、CSS，或者复制成图片；选中字体文件时先预览再安装"),
                      symbol: "textformat", category: .text, functions: [BuiltinPluginID.fontPreview],
                      // 和插件包里 FontPreviewModel 的键一样
                      defaultsKeys: ["pop.fontPreview.favorites", "pop.fontPreview.size"]),
        PluginPackage(id: "encryptFiles", bundleName: "PopEncryptFiles", name: String(localized: "加密打包"),
                      summary: String(localized: "把选中的文件和文件夹放进一个用密码加密（AES-256）的磁盘映像，在任何一台 Mac 上双击、输入密码就能打开；发给别人、存到 U 盘或者网盘前用"),
                      symbol: "lock.doc", category: .files, functions: [BuiltinPluginID.encryptFiles]),
        PluginPackage(id: "batteryInfo", bundleName: "PopBatteryInfo", name: String(localized: "电池信息"),
                      summary: String(localized: "看笔记本电池的电量、最大容量（健康度）、循环次数、状况、温度，正在充电或者耗电的功率、充电器多少瓦，还要多久充满或者用完；也列出连着的蓝牙键盘、鼠标、触控板和耳机的电量"),
                      symbol: "battery.100", category: .files, functions: [BuiltinPluginID.batteryInfo]),
        PluginPackage(id: "voiceRecorder", bundleName: "PopVoiceRecorder", name: String(localized: "录音"),
                      summary: String(localized: "用麦克风录一段声音，存成 .m4a 放进「下载」；录的时候屏幕上方有个小条，看得到时长和音量，可以暂停，录好能接着转成文字。正在录的时候再用一次就停止"),
                      symbol: "mic", category: .recording, functions: [BuiltinPluginID.voiceRecorder]),
    ]

    /// 插件包提供的所有功能
    static let functionIDs: Set<String> = Set(packages.flatMap(\.functions))

    static func package(id: String) -> PluginPackage? {
        packages.first { $0.id == id }
    }

    /// 提供这个功能的插件包；Pop 自带的功能返回 nil
    static func package(providing functionID: String) -> PluginPackage? {
        packages.first { $0.functions.contains(functionID) }
    }
}
