import AppKit
import Combine

/// 定时检查剪贴板变化（macOS 没有剪贴板变化的通知），把新内容记进历史。
@MainActor
final class ClipboardMonitor {
    /// 从剪贴板读到的原始内容。图片转 PNG 比较慢，放到后台做。
    enum Clip {
        case text(String)
        case files([URL])
        case image(Data, isPNG: Bool)
    }

    /// 密码管理器等 App 用这些类型标记「不要记录」的内容（nspasteboard.org 的约定）
    nonisolated static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
        NSPasteboard.PasteboardType("Pasteboard generator type"),
        NSPasteboard.PasteboardType("net.antelle.keeweb"),
    ]

    nonisolated static let maxTextBytes = 2 * 1024 * 1024
    nonisolated static let maxImageBytes = 30 * 1024 * 1024

    /// 记下了一条新内容（历史面板开着时据此刷新）
    var onRecord: (() -> Void)?

    private let store: ClipboardStore
    private var settings = ClipboardSettings()
    private var timer: Timer?
    private var lastChangeCount: Int
    /// 正在后台读剪贴板：读完（去掉跟踪参数的链接写回去以后）再接着看
    private var isReading = false
    /// 在这里读剪贴板的内容：别的 App 复制的大图、表格是要读的时候才现做的，要等那个 App 给；
    /// 那个 App 卡住时会一直等下去，放在主线程上 Pop 就跟着卡住了
    private static let readQueue = DispatchQueue(label: "io.github.whrss9527.pop.clipboard-read", qos: .utility)

    init(store: ClipboardStore) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func apply(_ settings: ClipboardSettings) {
        self.settings = settings
        // 只开了「复制链接时去掉跟踪参数」时也要盯着剪贴板
        if settings.enabled || settings.cleanLinks {
            start()
        } else {
            stop()
        }
    }

    private func start() {
        guard timer == nil else { return }
        // 不记录开启之前就在剪贴板里的内容
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.poll()
            }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func stop() {
        timer?.invalidate()
        timer = nil
    }

    func poll() {
        guard !isReading else { return }
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        switch PasteboardGuard.shared.verdict(for: changeCount) {
        case .busy:
            // Pop 正在读写剪贴板，等它结束再看
            return
        case .ignore:
            lastChangeCount = changeCount
            return
        case .record:
            lastChangeCount = changeCount
        }
        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let sourceApp, settings.ignoredBundleIDs.contains(sourceApp) { return }
        let settings = settings
        isReading = true
        Self.readQueue.async { [weak self] in
            guard let copied = Self.read(pasteboard, recordImages: settings.enabled && settings.recordImages) else {
                DispatchQueue.main.async { [weak self] in
                    MainActor.assumeIsolated { self?.isReading = false }
                }
                return
            }
            var clip = copied
            var written: Int?
            if settings.cleanLinks, case .text(let text) = copied, let cleaned = LinkInspector.cleanedLink(in: text) {
                // 复制的是带跟踪参数的链接：换成去掉参数的，自己这次写入不再处理
                pasteboard.clearContents()
                pasteboard.setString(cleaned, forType: .string)
                written = pasteboard.changeCount
                clip = .text(cleaned)
            }
            DispatchQueue.main.async { [weak self] in
                MainActor.assumeIsolated {
                    guard let self else { return }
                    self.isReading = false
                    if let written {
                        self.lastChangeCount = written
                    }
                    if settings.enabled {
                        self.record(clip, sourceApp: sourceApp)
                    }
                }
            }
        }
    }

    /// 记进历史：转 PNG、存数据库、认图片里的字都在后台
    private func record(_ clip: Clip, sourceApp: String?) {
        let store = self.store
        let indexImages = settings.searchImageText
        DispatchQueue.global(qos: .utility).async { [weak self] in
            guard let capture = Self.capture(clip, sourceApp: sourceApp), let id = store.add(capture) else { return }
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                    self?.onRecord?()
                }
            }
            if indexImages, capture.kind == .image, let png = capture.imagePNG {
                ClipboardImageIndex.index(png: png, id: id, store: store)
            }
        }
    }

    /// 在读剪贴板的线程上
    nonisolated static func read(_ pasteboard: NSPasteboard, recordImages: Bool) -> Clip? {
        let types = pasteboard.types ?? []
        guard !types.contains(where: { ignoredTypes.contains($0) }) else { return nil }
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // 两步验证的链接里有密钥，不记
            guard !containsSecretLink(string) else { return nil }
            return string.utf8.count <= maxTextBytes ? .text(string) : nil
        }
        guard recordImages else { return nil }
        if let png = pasteboard.data(forType: .png) {
            return png.count <= maxImageBytes ? .image(png, isPNG: true) : nil
        }
        if let tiff = pasteboard.data(forType: .tiff) {
            return tiff.count <= maxImageBytes * 4 ? .image(tiff, isPNG: false) : nil
        }
        return nil
    }

    /// 有没有两步验证的链接（otpauth://、otpauth-migration://）：里面写着密钥
    nonisolated static func containsSecretLink(_ text: String) -> Bool {
        text.range(of: "otpauth(-migration)?://", options: [.regularExpression, .caseInsensitive]) != nil
    }

    nonisolated static func capture(_ clip: Clip, sourceApp: String?) -> ClipboardCapture? {
        switch clip {
        case .text(let text):
            return ClipboardCapture(kind: .text, text: text, sourceApp: sourceApp)
        case .files(let urls):
            let paths = urls.map { $0.path(percentEncoded: false) }.joined(separator: "\n")
            return ClipboardCapture(kind: .files, text: paths, sourceApp: sourceApp)
        case .image(let data, let isPNG):
            let png = isPNG ? data : NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
            guard let png, png.count <= maxImageBytes else { return nil }
            return ClipboardCapture(kind: .image, text: "", imagePNG: png, sourceApp: sourceApp)
        }
    }
}

/// 剪贴板历史的对外接口：记录、查询、粘贴、定期清理。设置页和历史面板都用它。
@MainActor
final class ClipboardService: ObservableObject {
    let store: ClipboardStore
    private let monitor: ClipboardMonitor
    private(set) var settings = ClipboardSettings()
    @Published private(set) var itemCount = 0
    @Published private(set) var totalBytes = 0
    /// 历史有变化（新记录、删除、清理）
    let changes = PassthroughSubject<Void, Never>()

    private var cleanupTimer: Timer?
    private var backfillStarted = false

    init(store: ClipboardStore = ClipboardStore()) {
        self.store = store
        monitor = ClipboardMonitor(store: store)
        monitor.onRecord = { [weak self] in
            self?.didChange()
        }
    }

    var isEnabled: Bool { settings.enabled }

    func apply(_ settings: ClipboardSettings) {
        let previous = self.settings
        self.settings = settings
        monitor.apply(settings)
        if settings.enabled, settings.searchImageText, !backfillStarted {
            // 以前记下的图片补上文字识别，慢慢做，不和别的事抢
            backfillStarted = true
            let store = self.store
            DispatchQueue.global(qos: .background).async {
                ClipboardImageIndex.backfill(store: store)
            }
        }
        if cleanupTimer == nil {
            // 启动时清理一次，之后每小时一次
            let timer = Timer(timeInterval: 3600, repeats: true) { [weak self] _ in
                MainActor.assumeIsolated {
                    self?.cleanup()
                }
            }
            RunLoop.main.add(timer, forMode: .common)
            cleanupTimer = timer
            cleanup()
        } else if previous.retentionDays != settings.retentionDays || previous.maxItems != settings.maxItems {
            cleanup()
        }
    }

    func cleanup() {
        let store = self.store
        let settings = self.settings
        DispatchQueue.global(qos: .utility).async { [weak self] in
            store.cleanup(retentionDays: settings.retentionDays, maxItems: settings.maxItems)
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                    self?.didChange()
                }
            }
        }
    }

    func items(matching search: String, limit: Int = 300) -> [ClipboardItem] {
        store.items(matching: search, limit: limit)
    }

    /// 在数据库的队列上查，调用的线程不用等
    func searchItems(matching search: String, limit: Int = 300) async -> [ClipboardItem] {
        await store.searchItems(matching: search, limit: limit)
    }

    func setPinned(_ pinned: Bool, item: ClipboardItem) {
        store.setPinned(pinned, id: item.id)
        didChange()
    }

    func delete(_ item: ClipboardItem) {
        store.delete(id: item.id)
        didChange()
    }

    func clear(keepPinned: Bool) {
        store.clear(keepPinned: keepPinned)
        didChange()
    }

    func refreshStatistics() {
        let statistics = store.statistics()
        if itemCount != statistics.count {
            itemCount = statistics.count
        }
        if totalBytes != statistics.bytes {
            totalBytes = statistics.bytes
        }
    }

    /// 把一条历史写回剪贴板并粘贴到前台 App（调用前要先收起浮窗）。
    func paste(_ item: ClipboardItem) {
        let imageURL = store.imageURL(for: item)
        Paster.paste(restoringPrevious: false) { pasteboard in
            Self.write(item, imageURL: imageURL, to: pasteboard)
        }
        store.markUsed(id: item.id)
    }

    /// 复制一段文字（比如多选合起来的几条），会作为新的一条记进历史
    func copy(text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    /// 只复制，不粘贴。
    func copy(_ item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        Self.write(item, imageURL: store.imageURL(for: item), to: pasteboard)
        store.markUsed(id: item.id)
    }

    private static func write(_ item: ClipboardItem, imageURL: URL?, to pasteboard: NSPasteboard) {
        switch item.kind {
        case .text:
            pasteboard.setString(item.text, forType: .string)
        case .files:
            pasteboard.writeObjects(item.fileURLs as [NSURL])
        case .image:
            guard let imageURL, let png = try? Data(contentsOf: imageURL) else { return }
            pasteboard.setData(png, forType: .png)
            if let tiff = NSImage(data: png)?.tiffRepresentation {
                pasteboard.setData(tiff, forType: .tiff)
            }
        }
    }

    private func didChange() {
        refreshStatistics()
        changes.send()
    }
}

/// 给剪贴板历史里的图片识别文字，搜索时用。都在本机做，不联网。
enum ClipboardImageIndex {
    /// 刚记下的图片；同样的图片以前识别过就不再识别
    static func index(png: Data, id: Int64, store: ClipboardStore) {
        guard store.item(id: id)?.recognizedText == nil else { return }
        guard let image = TextRecognizer.cgImage(from: png) else {
            store.setRecognizedText("", id: id)
            return
        }
        store.setRecognizedText((try? TextRecognizer.recognizeLines(in: image)) ?? "", id: id)
    }

    /// 以前记下、还没识别过的图片补上（每次最多 limit 张，最近用过的先做）
    static func backfill(store: ClipboardStore, limit: Int = 300) {
        for item in store.imagesWithoutRecognizedText(limit: limit) {
            guard let url = store.imageURL(for: item), let image = TextRecognizer.cgImage(contentsOf: url) else {
                store.setRecognizedText("", id: item.id)
                continue
            }
            store.setRecognizedText((try? TextRecognizer.recognizeLines(in: image)) ?? "", id: item.id)
        }
    }
}
