import AppKit
import Combine

/// 定时检查剪贴板变化（macOS 没有剪贴板变化的通知），把新内容记进历史。
@MainActor
final class ClipboardMonitor {
    /// 从剪贴板读到的原始内容。图片转 PNG 比较慢，放到后台做。
    enum Clip {
        case text(String)
        case files([URL])
        case image(Data, isPNG: Bool)
    }

    /// 密码管理器等 App 用这些类型标记「不要记录」的内容（nspasteboard.org 的约定）
    static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
        NSPasteboard.PasteboardType("Pasteboard generator type"),
        NSPasteboard.PasteboardType("net.antelle.keeweb"),
    ]

    nonisolated static let maxTextBytes = 2 * 1024 * 1024
    nonisolated static let maxImageBytes = 30 * 1024 * 1024

    /// 记下了一条新内容（历史面板开着时据此刷新）
    var onRecord: (() -> Void)?

    private let store: ClipboardStore
    private var settings = ClipboardSettings()
    private var timer: Timer?
    private var lastChangeCount: Int

    init(store: ClipboardStore) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func apply(_ settings: ClipboardSettings) {
        self.settings = settings
        if settings.enabled {
            start()
        } else {
            stop()
        }
    }

    private func start() {
        guard timer == nil else { return }
        // 不记录开启之前就在剪贴板里的内容
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.poll()
            }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func stop() {
        timer?.invalidate()
        timer = nil
    }

    func poll() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        switch PasteboardGuard.shared.verdict(for: changeCount) {
        case .busy:
            // Pop 正在读写剪贴板，等它结束再看
            return
        case .ignore:
            lastChangeCount = changeCount
            return
        case .record:
            lastChangeCount = changeCount
        }
        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let sourceApp, settings.ignoredBundleIDs.contains(sourceApp) { return }
        guard let clip = Self.read(pasteboard, recordImages: settings.recordImages) else { return }
        let store = self.store
        DispatchQueue.global(qos: .utility).async { [weak self] in
            guard let capture = Self.capture(clip, sourceApp: sourceApp), store.add(capture) != nil else { return }
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                    self?.onRecord?()
                }
            }
        }
    }

    static func read(_ pasteboard: NSPasteboard, recordImages: Bool) -> Clip? {
        let types = pasteboard.types ?? []
        guard !types.contains(where: { ignoredTypes.contains($0) }) else { return nil }
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return string.utf8.count <= maxTextBytes ? .text(string) : nil
        }
        guard recordImages else { return nil }
        if let png = pasteboard.data(forType: .png) {
            return png.count <= maxImageBytes ? .image(png, isPNG: true) : nil
        }
        if let tiff = pasteboard.data(forType: .tiff) {
            return tiff.count <= maxImageBytes * 4 ? .image(tiff, isPNG: false) : nil
        }
        return nil
    }

    nonisolated static func capture(_ clip: Clip, sourceApp: String?) -> ClipboardCapture? {
        switch clip {
        case .text(let text):
            return ClipboardCapture(kind: .text, text: text, sourceApp: sourceApp)
        case .files(let urls):
            let paths = urls.map { $0.path(percentEncoded: false) }.joined(separator: "\n")
            return ClipboardCapture(kind: .files, text: paths, sourceApp: sourceApp)
        case .image(let data, let isPNG):
            let png = isPNG ? data : NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
            guard let png, png.count <= maxImageBytes else { return nil }
            return ClipboardCapture(kind: .image, text: "", imagePNG: png, sourceApp: sourceApp)
        }
    }
}

/// 剪贴板历史的对外接口：记录、查询、粘贴、定期清理。设置页和历史面板都用它。
@MainActor
final class ClipboardService: ObservableObject {
    let store: ClipboardStore
    private let monitor: ClipboardMonitor
    private(set) var settings = ClipboardSettings()
    @Published private(set) var itemCount = 0
    @Published private(set) var totalBytes = 0
    /// 历史有变化（新记录、删除、清理）
    let changes = PassthroughSubject<Void, Never>()

    private var cleanupTimer: Timer?

    init(store: ClipboardStore = ClipboardStore()) {
        self.store = store
        monitor = ClipboardMonitor(store: store)
        monitor.onRecord = { [weak self] in
            self?.didChange()
        }
    }

    var isEnabled: Bool { settings.enabled }

    func apply(_ settings: ClipboardSettings) {
        let previous = self.settings
        self.settings = settings
        monitor.apply(settings)
        if cleanupTimer == nil {
            // 启动时清理一次，之后每小时一次
            let timer = Timer(timeInterval: 3600, repeats: true) { [weak self] _ in
                MainActor.assumeIsolated {
                    self?.cleanup()
                }
            }
            RunLoop.main.add(timer, forMode: .common)
            cleanupTimer = timer
            cleanup()
        } else if previous.retentionDays != settings.retentionDays || previous.maxItems != settings.maxItems {
            cleanup()
        }
    }

    func cleanup() {
        let store = self.store
        let settings = self.settings
        DispatchQueue.global(qos: .utility).async { [weak self] in
            store.cleanup(retentionDays: settings.retentionDays, maxItems: settings.maxItems)
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                    self?.didChange()
                }
            }
        }
    }

    func items(matching search: String, limit: Int = 300) -> [ClipboardItem] {
        store.items(matching: search, limit: limit)
    }

    func setPinned(_ pinned: Bool, item: ClipboardItem) {
        store.setPinned(pinned, id: item.id)
        didChange()
    }

    func delete(_ item: ClipboardItem) {
        store.delete(id: item.id)
        didChange()
    }

    func clear(keepPinned: Bool) {
        store.clear(keepPinned: keepPinned)
        didChange()
    }

    func refreshStatistics() {
        let statistics = store.statistics()
        if itemCount != statistics.count {
            itemCount = statistics.count
        }
        if totalBytes != statistics.bytes {
            totalBytes = statistics.bytes
        }
    }

    /// 把一条历史写回剪贴板并粘贴到前台 App（调用前要先收起浮窗）。
    func paste(_ item: ClipboardItem) {
        let imageURL = store.imageURL(for: item)
        Paster.paste(restoringPrevious: false) { pasteboard in
            Self.write(item, imageURL: imageURL, to: pasteboard)
        }
        store.markUsed(id: item.id)
    }

    /// 只复制，不粘贴。
    func copy(_ item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        Self.write(item, imageURL: store.imageURL(for: item), to: pasteboard)
        store.markUsed(id: item.id)
    }

    private static func write(_ item: ClipboardItem, imageURL: URL?, to pasteboard: NSPasteboard) {
        switch item.kind {
        case .text:
            pasteboard.setString(item.text, forType: .string)
        case .files:
            pasteboard.writeObjects(item.fileURLs as [NSURL])
        case .image:
            guard let imageURL, let png = try? Data(contentsOf: imageURL) else { return }
            pasteboard.setData(png, forType: .png)
            if let tiff = NSImage(data: png)?.tiffRepresentation {
                pasteboard.setData(tiff, forType: .tiff)
            }
        }
    }

    private func didChange() {
        refreshStatistics()
        changes.send()
    }
}
